#!/bin/bash
# since Bash v4
rm data/out/*
touch temp
echo "Name of file:"
read name
echo "Number of tests:"
read number
echo "Do you want to perform Valgrind tests? y/n"
read valgrind_test
gcc -pedantic -Wall -Werror -std=c99 -O3 $name -o test2

echo " "
echo "/*------------------------------------------------------------*/"
echo " "


if [ $valgrind_test = 'Y' -o $valgrind_test = 'y' ]; then
	for ((i=1; i<=number;i++))
	do
		echo "MANDATORY - PUB0$i"
		echo " "
		valgrind --leak-check=yes -q ./test2 < data/man/pub0$i-m.in > temp
		echo " "
		# echo "OPTIONAL - PUB0$i"
		# echo " "
		# valgrind --leak-check=yes -q ./test2 < data/opt/pub0$i-o.in > temp
		# echo " "
		# echo "/*------------------------------------------------------------*/"
		# echo " "
		time ./test2 < data/man/pub0$i-m.in > data/out/pub0$i-m.out 2> data/out/pub0$i-m.err
		# ./test2 < data/opt/pub0$i-o.in > data/out/pub0$i-o.out 2> data/out/pub0$i-o.err
	done
else
    for ((i=1; i<=number;i++))
	do
		time ./test2 < data/man/pub0$i-m.in > data/out/pub0$i-m.out 2> data/out/pub0$i-m.err
		# ./test2 < data/opt/pub0$i-o.in > data/out/pub0$i-o.out 2> data/out/pub0$i-o.err
	done
fi

echo "CMP test"
echo " "
for ((i=1; i<=number;i++))
	do
		# cmp -b data/opt/pub0$i-o.out data/out/pub0$i-o.out
		# cmp -b data/opt/pub0$i-o.err data/out/pub0$i-o.err
		cmp -b data/man/pub0$i-m.out data/out/pub0$i-m.out
		cmp -b data/man/pub0$i-m.err data/out/pub0$i-m.err
	done
echo " "
echo "/*------------------------------------------------------------*/"
echo " "
echo "Tests done"
rm test2
rm temp


